export const movies = [
  {
    id: '1',
    title: 'Neon Dreams',
    synopsis: 'A cyberpunk thriller set in a futuristic Tokyo where memories can be bought and sold. Following a memory-broker who stumbles upon a conspiracy.',
    duration: '24m',
    year: 2026,
    director: 'Kaito Tanaka',
    rating: 4.8,
    genre: ['Sci-Fi', 'Thriller'],
    thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1920&auto=format&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    isTrending: true,
    isFeatured: true
  },
  {
    id: '2',
    title: 'The Last Oasis',
    synopsis: 'In a world parched by decades of drought, a young scavenger discovers a hidden valley teeming with life. Now she must protect it.',
    duration: '18m',
    year: 2025,
    director: 'Sarah Jenkins',
    rating: 4.5,
    genre: ['Post-Apocalyptic', 'Drama'],
    thumbnail: 'https://images.unsplash.com/photo-1469521669194-bce261563d23?q=80&w=1920&auto=format&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    isTrending: true,
    isFeatured: false
  },
  {
    id: '3',
    title: 'Midnight Serenade',
    synopsis: 'Two rival jazz musicians in 1920s New Orleans find themselves competing for the same gig, only to realize they play better together.',
    duration: '15m',
    year: 2026,
    director: 'Marcus Cole',
    rating: 4.9,
    genre: ['Music', 'Romance'],
    thumbnail: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?q=80&w=1920&auto=format&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    isTrending: false,
    isFeatured: false
  },
  {
    id: '4',
    title: 'Echoes of the Deep',
    synopsis: 'An oceanographer investigating anomalous whale songs discovers something that shouldn\'t be there.',
    duration: '32m',
    year: 2024,
    director: 'Elena Rostova',
    rating: 4.7,
    genre: ['Mystery', 'Sci-Fi'],
    thumbnail: 'https://images.unsplash.com/photo-1518010228300-8dceaa193ba1?q=80&w=1920&auto=format&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    isTrending: true,
    isFeatured: false
  },
  {
    id: '5',
    title: 'Concrete Jungle',
    synopsis: 'A high-stakes parkour chase through the slums of Rio de Janeiro. A visual masterpiece of movement and cinematography.',
    duration: '12m',
    year: 2025,
    director: 'Tiago Silva',
    rating: 4.6,
    genre: ['Action', 'Documentary'],
    thumbnail: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1920&auto=format&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    isTrending: false,
    isFeatured: false
  },
  {
    id: '6',
    title: 'Shadow Protocol',
    synopsis: 'An operative goes rogue in a high-tech Berlin, trying to expose an AI-driven global surveillance program.',
    duration: '22m',
    year: 2026,
    director: 'Marcus Cole',
    rating: 4.7,
    genre: ['Thriller', 'Action'],
    thumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1920&auto=format&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    isTrending: true,
    isFeatured: false
  },
  {
    id: '7',
    title: 'Whispers of Autumn',
    synopsis: 'A quiet, beautifully shot story of two strangers who meet on a train in Kyoto during the autumn leaf season and share their deepest life regrets.',
    duration: '16m',
    year: 2025,
    director: 'Yuki Sato',
    rating: 4.4,
    genre: ['Drama', 'Romance'],
    thumbnail: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=1920&auto=format&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    isTrending: false,
    isFeatured: false
  },
  {
    id: '8',
    title: 'Submerged Echo',
    synopsis: 'An emotional journey of a free-diver returning to the deep cave where her brother went missing, only to find a mysterious message left in the rock.',
    duration: '20m',
    year: 2024,
    director: 'Elena Rostova',
    rating: 4.6,
    genre: ['Mystery', 'Drama'],
    thumbnail: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1920&auto=format&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    isTrending: false,
    isFeatured: false
  },
  {
    id: '9',
    title: 'Skyline High',
    synopsis: 'Follow three daredevil high-liners as they attempt to walk a slackline suspended between two cloud-kissed peaks in the Swiss Alps.',
    duration: '28m',
    year: 2026,
    director: 'Tiago Silva',
    rating: 4.9,
    genre: ['Action', 'Documentary'],
    thumbnail: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1920&auto=format&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    isTrending: true,
    isFeatured: false
  },
  {
    id: '10',
    title: 'The Algorithm of You',
    synopsis: 'In a near future where love is curated by a perfect predictive algorithm, a glitch causes two completely incompatible people to fall in love.',
    duration: '19m',
    year: 2025,
    director: 'Sarah Jenkins',
    rating: 4.8,
    genre: ['Sci-Fi', 'Romance'],
    thumbnail: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?q=80&w=1920&auto=format&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    isTrending: false,
    isFeatured: false
  },
  {
    id: '11',
    title: 'Rhythm & Ash',
    synopsis: 'A nomadic cellist travels across a scorched volcanic wasteland, playing concertos to bring hope to scattered survivor outposts.',
    duration: '25m',
    year: 2026,
    director: 'Marcus Cole',
    rating: 4.7,
    genre: ['Music', 'Post-Apocalyptic'],
    thumbnail: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?q=80&w=1920&auto=format&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    isTrending: false,
    isFeatured: false
  },
  {
    id: '12',
    title: 'Midnight Tokyo',
    synopsis: 'A late-night radio DJ receives a series of cryptic, coded phone calls during her broadcast that predict events happening in real-time on the streets.',
    duration: '14m',
    year: 2026,
    director: 'Kaito Tanaka',
    rating: 4.5,
    genre: ['Thriller', 'Mystery'],
    thumbnail: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=1920&auto=format&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    isTrending: true,
    isFeatured: false
  },
  {
    id: '13',
    title: 'Stardust Wanderer',
    synopsis: 'A lonely astronaut on a multi-generational spaceship deals with the psychological toll of being the sole keeper of Earth\'s digital art archive.',
    duration: '35m',
    year: 2025,
    director: 'Elena Rostova',
    rating: 4.9,
    genre: ['Sci-Fi', 'Drama'],
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1920&auto=format&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    isTrending: true,
    isFeatured: false
  },
  {
    id: '14',
    title: 'The Beat Goes On',
    synopsis: 'An intimate look into the underground techno scene of Berlin, exploring how modular synthesis became a form of shared therapeutic expression.',
    duration: '30m',
    year: 2024,
    director: 'Tiago Silva',
    rating: 4.6,
    genre: ['Music', 'Documentary'],
    thumbnail: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=1920&auto=format&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    isTrending: false,
    isFeatured: false
  },
  {
    id: '15',
    title: 'Dust & Glory',
    synopsis: 'A high-octane sand-buggy race across the endless dunes of the Mojave desert, where the ultimate prize is a single barrel of clean water.',
    duration: '17m',
    year: 2025,
    director: 'Sarah Jenkins',
    rating: 4.7,
    genre: ['Action', 'Post-Apocalyptic'],
    thumbnail: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?q=80&w=1920&auto=format&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    isTrending: true,
    isFeatured: false
  }
]

export const creators = [
  {
    id: 'c1',
    name: 'Kaito Tanaka',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=150&auto=format&fit=crop',
    followers: '12.4K',
    bio: 'Visionary sci-fi director exploring the intersection of humanity and technology through neon cyber-aesthetics.'
  },
  {
    id: 'c2',
    name: 'Sarah Jenkins',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150&auto=format&fit=crop',
    followers: '8.2K',
    bio: 'Award-winning post-apocalyptic storyteller focusing on raw, human survival and environmental narratives.'
  },
  {
    id: 'c3',
    name: 'Marcus Cole',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150&auto=format&fit=crop',
    followers: '15.1K',
    bio: 'Multi-disciplinary director bridging the gap between musical scores, emotional romances, and intense thrillers.'
  },
  {
    id: 'c4',
    name: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=150&auto=format&fit=crop',
    followers: '9.6K',
    bio: 'Siberian-born indie filmmaker creating quiet, high-concept philosophical science fiction and slow mysteries.'
  },
  {
    id: 'c5',
    name: 'Tiago Silva',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=150&auto=format&fit=crop',
    followers: '11.0K',
    bio: 'Action-sports cinematographer dedicated to exploring high-intensity human movement in urban jungles and massive peaks.'
  },
  {
    id: 'c6',
    name: 'Yuki Sato',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150&auto=format&fit=crop',
    followers: '7.8K',
    bio: 'Indie drama director specializing in delicate human relationships, cultural dialogues, and gorgeous seasonal photography.'
  }
]
